use std::error::Error;

pub async fn get_order_pairs() -> Result<(), Box<dyn Error>> {

    Ok(())
}